#!/usr/bin/env python3
"""async_build — HFT scaffold builder for async trade management.

Renders hft-async scaffold with CAsyncTradeManager integration.
Usage: mql5-async-build --name FastScalper --output ./output [--stack netting]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HFT_TEMPLATE = """//+------------------------------------------------------------------+
//| {name}.mq5 — HFT Async EA (generated by async_build)             |
//+------------------------------------------------------------------+
#property copyright "vibecodekit-mql5-ea"
#property version   "1.00"
#property strict

#include <vibecodekit\\CAsyncTradeManager.mqh>
#include <vibecodekit\\CPipNormalizer.mqh>
#include <vibecodekit\\CRiskGuard.mqh>
#include <vibecodekit\\CSpreadGuard.mqh>

input int    InpMagic         = 12345;
input double InpRiskPercent   = 1.0;
input int    InpMaxSpreadPips = 3;
input int    InpSLPips        = 15;
input int    InpTPPips        = 30;

CAsyncTradeManager g_async;
CPipNormalizer     g_pip;
CRiskGuard         g_risk;
CSpreadGuard       g_spread;

int OnInit()
{{
    g_pip.Init(_Symbol, _Digits);
    g_risk.Init(5.0, 3, InpMagic);
    g_spread.Init(_Symbol, InpMaxSpreadPips, g_pip.PipSize());
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason) {{ }}

void OnTick()
{{
    if(!g_risk.CanOpenTrade()) return;
    if(!g_spread.IsSpreadOK()) return;

    double sl_pts = g_pip.Pips(InpSLPips);
    double tp_pts = g_pip.Pips(InpTPPips);
    double lot = g_pip.LotForRisk(InpRiskPercent, InpSLPips);

    // HFT signal logic — replace with your fast-signal engine
    // g_async.SendBuyAsync(_Symbol, lot, sl_pts, tp_pts, InpMagic, "{name}");
}}

void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result)
{{
    g_async.OnTransactionResult(trans, request, result);
}}
//+------------------------------------------------------------------+
"""


def build_hft_scaffold(name: str, output: Path, stack: str) -> dict:
    ea_dir = output / name
    ea_dir.mkdir(parents=True, exist_ok=True)
    ea_file = ea_dir / f"{name}.mq5"
    content = HFT_TEMPLATE.format(name=name)
    ea_file.write_text(content)

    sets_dir = ea_dir / "Sets"
    sets_dir.mkdir(exist_ok=True)
    (sets_dir / "default.set").write_text(
        "; HFT Async defaults\n"
        "InpMagic=12345||10000||99999||1\n"
        "InpRiskPercent=1.0||0.5||3.0||0.5\n"
        "InpMaxSpreadPips=3||1||10||1\n"
        "InpSLPips=15||5||50||5\n"
        "InpTPPips=30||10||100||10\n"
    )

    return {
        "success": True,
        "name": name,
        "stack": stack,
        "files": [str(ea_file), str(sets_dir / "default.set")],
        "includes": ["CAsyncTradeManager", "CPipNormalizer", "CRiskGuard", "CSpreadGuard"],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="HFT async scaffold builder")
    parser.add_argument("--name", required=True, help="EA name")
    parser.add_argument("--output", type=Path, default=Path("./output"))
    parser.add_argument("--stack", default="netting", choices=["netting", "hedging"])
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    result = build_hft_scaffold(args.name, args.output, args.stack)
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"HFT scaffold: {args.name} ({args.stack})")
        for f in result["files"]:
            print(f"  {f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
