#!/usr/bin/env python3
"""onnx_embed — Generate #resource directive + COnnxLoader integration.

Reads an .onnx file, generates MQL5 code to embed and load it.
Usage: mql5-onnx-embed --onnx model.onnx --ea EA.mq5
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

RESOURCE_TEMPLATE = '#resource "\\\\Models\\\\{model_name}" as uchar {resource_var}[]'

LOADER_TEMPLATE = """// Auto-generated by mql5-onnx-embed
#include <vibecodekit\\COnnxLoader.mqh>
#resource "\\\\Models\\\\{model_name}" as uchar ExtModel[]

COnnxLoader g_onnx;

bool InitOnnxModel()
{{
    if(!g_onnx.LoadFromResource(ExtModel))
    {{
        PrintFormat("[ONNX] Failed to load model: {model_name}");
        return false;
    }}
    long input_shape[] = {{{input_shape_str}}};
    g_onnx.SetInputShape(input_shape);
    return true;
}}

double PredictSignal(double &features[])
{{
    double output[];
    if(!g_onnx.Predict(features, output))
        return 0.0;
    return output[0];
}}"""


def generate_embed(onnx_path: Path, ea_path: Path | None = None,
                   input_shape: list[int] | None = None) -> dict:
    if not onnx_path.exists():
        return {"success": False, "error": f"ONNX file not found: {onnx_path}"}

    model_name = onnx_path.name
    file_size = onnx_path.stat().st_size
    shape = input_shape or [1, 10]
    shape_str = ", ".join(str(s) for s in shape)

    resource_line = RESOURCE_TEMPLATE.format(model_name=model_name, resource_var="ExtModel")
    loader_code = LOADER_TEMPLATE.format(
        model_name=model_name, input_shape_str=shape_str,
    )

    result = {
        "success": True,
        "model": model_name,
        "size_bytes": file_size,
        "resource_directive": resource_line,
        "input_shape": shape,
        "loader_code": loader_code,
    }

    if ea_path and ea_path.exists():
        content = ea_path.read_text(encoding="utf-8", errors="replace")
        if "#resource" in content and model_name in content:
            result["already_embedded"] = True
        else:
            result["already_embedded"] = False
            result["instruction"] = f"Add to top of {ea_path.name}:\n{resource_line}"

    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Embed ONNX model in EA")
    parser.add_argument("--onnx", type=Path, required=True, help=".onnx file")
    parser.add_argument("--ea", type=Path, default=None, help=".mq5 file")
    parser.add_argument("--input-shape", type=str, default=None, help="e.g. 1,10")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    shape = [int(x) for x in args.input_shape.split(",")] if args.input_shape else None
    result = generate_embed(args.onnx, args.ea, shape)

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        if result["success"]:
            print(f"Model: {result['model']} ({result['size_bytes']} bytes)")
            print(f"Resource: {result['resource_directive']}")
            print(f"\n--- Loader code ---\n{result['loader_code']}")
        else:
            print(f"Error: {result['error']}")

    return 0 if result["success"] else 1


if __name__ == "__main__":
    sys.exit(main())
