//+------------------------------------------------------------------+
//| EAName.mq5 — Standard Library EA with Python bridge              |
//| Generated by vibecodekit-mql5-ea scaffold                        |
//+------------------------------------------------------------------+
#property copyright "EAName"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include "CPipNormalizer.mqh"
#include "CRiskGuard.mqh"

input int    InpMagic       = 12345;
input double InpRiskPercent = 1.0;
input int    InpSLPips      = 50;
input int    InpTPPips      = 100;
input int    InpMaxPos      = 3;
input string InpPythonURL   = "http://127.0.0.1:5000/signal";

const double DailyLossLimit = 5.0;

CTrade         trade;
CPipNormalizer pipNorm;
CRiskGuard     riskGuard;

int OnInit()
{
    if(!pipNorm.Init(_Symbol))   return INIT_FAILED;
    if(!riskGuard.Init(DailyLossLimit, InpMaxPos, InpMagic, "EAName"))
        return INIT_FAILED;

    trade.SetExpertMagicNumber(InpMagic);
    EventSetTimer(60);
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) { EventKillTimer(); }

void OnTimer()
{
    // Call Python bridge on timer (not OnTick — AP-17 compliant)
    if(!riskGuard.CanOpenTrade()) return;

    string headers = "Content-Type: application/json\r\n";
    string body    = "{\"symbol\":\"" + _Symbol + "\"}";
    char   data[];
    char   result[];
    string result_headers;

    StringToCharArray(body, data);
    int res = WebRequest("POST", InpPythonURL, headers, 5000, data,
                         result, result_headers);

    if(res != 200) return;

    string response = CharArrayToString(result);
    // Parse response: {"signal":"buy"} or {"signal":"sell"} or {"signal":"none"}
    if(StringFind(response, "\"buy\"") >= 0)
    {
        double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double sl  = ask - pipNorm.Pips(InpSLPips);
        double tp  = ask + pipNorm.Pips(InpTPPips);
        double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk_money, InpSLPips);
        trade.Buy(lots, _Symbol, ask, sl, tp, "EAName py-buy");
    }
    else if(StringFind(response, "\"sell\"") >= 0)
    {
        double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double sl  = bid + pipNorm.Pips(InpSLPips);
        double tp  = bid - pipNorm.Pips(InpTPPips);
        double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk_money, InpSLPips);
        trade.Sell(lots, _Symbol, bid, sl, tp, "EAName py-sell");
    }
}
//+------------------------------------------------------------------+
