//+------------------------------------------------------------------+
//| XauScalperEA.mq5 — XAUUSD H4 scalping EA (hedging mode)        |
//| Strategy: EMA 9/21 crossover + RSI(14) filter                   |
//| Generated by vibecodekit-mql5-ea scaffold · Phase D              |
//+------------------------------------------------------------------+
#property copyright "XauScalperEA — vibecodekit-mql5-ea"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include "CPipNormalizer.mqh"
#include "CRiskGuard.mqh"
#include "CMagicRegistry.mqh"

input int    InpMagic       = 77001;
input double InpRiskPercent = 1.0;
input int    InpSLPips      = 300;
input int    InpTPPips      = 600;

CTrade         trade;
CPipNormalizer pipNorm;
CRiskGuard     riskGuard;
CMagicRegistry magicReg;

int hEmaFast, hEmaSlow, hRsi;

int OnInit()
{
    if(!pipNorm.Init(_Symbol)) return INIT_FAILED;
    if(!riskGuard.Init(5.0, 3, InpMagic, "XauScalperEA")) return INIT_FAILED;
    if(!magicReg.Register(InpMagic, "XauScalperEA")) return INIT_FAILED;
    trade.SetExpertMagicNumber(InpMagic);

    hEmaFast = iMA(_Symbol, PERIOD_H4, 9, 0, MODE_EMA, PRICE_CLOSE);
    hEmaSlow = iMA(_Symbol, PERIOD_H4, 21, 0, MODE_EMA, PRICE_CLOSE);
    hRsi     = iRSI(_Symbol, PERIOD_H4, 14, PRICE_CLOSE);

    if(hEmaFast == INVALID_HANDLE || hEmaSlow == INVALID_HANDLE
       || hRsi == INVALID_HANDLE)
        return INIT_FAILED;

    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
    if(hEmaFast != INVALID_HANDLE) IndicatorRelease(hEmaFast);
    if(hEmaSlow != INVALID_HANDLE) IndicatorRelease(hEmaSlow);
    if(hRsi     != INVALID_HANDLE) IndicatorRelease(hRsi);
    magicReg.Unregister(InpMagic);
}

void OnTick()
{
    if(!riskGuard.CanOpenTrade()) return;

    double fast[], slow[], rsi[];
    if(CopyBuffer(hEmaFast, 0, 0, 3, fast) < 3) return;
    if(CopyBuffer(hEmaSlow, 0, 0, 3, slow) < 3) return;
    if(CopyBuffer(hRsi, 0, 0, 2, rsi)     < 2) return;

    bool crossUp   = fast[1] > slow[1] && fast[2] <= slow[2];
    bool crossDown = fast[1] < slow[1] && fast[2] >= slow[2];
    bool rsiOK_buy  = rsi[1] > 30.0 && rsi[1] < 70.0;
    bool rsiOK_sell = rsi[1] > 30.0 && rsi[1] < 70.0;

    if(crossUp && rsiOK_buy)
    {
        double ask  = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double sl   = ask - pipNorm.Pips(InpSLPips);
        double tp   = ask + pipNorm.Pips(InpTPPips);
        double risk = AccountInfoDouble(ACCOUNT_BALANCE)
                      * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk, InpSLPips);

        trade.Buy(lots, _Symbol, ask, sl, tp, "XauScalp buy");
        PrintFormat("BUY %.2f lots @ %.2f SL=%.2f TP=%.2f",
                    lots, ask, sl, tp);
    }

    if(crossDown && rsiOK_sell)
    {
        double bid  = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double sl   = bid + pipNorm.Pips(InpSLPips);
        double tp   = bid - pipNorm.Pips(InpTPPips);
        double risk = AccountInfoDouble(ACCOUNT_BALANCE)
                      * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk, InpSLPips);

        trade.Sell(lots, _Symbol, bid, sl, tp, "XauScalp sell");
        PrintFormat("SELL %.2f lots @ %.2f SL=%.2f TP=%.2f",
                    lots, bid, sl, tp);
    }
}
//+------------------------------------------------------------------+
