#!/usr/bin/env bash
# build_reference_report.sh — Regenerate docs/reference-ea/REPORT.md from a freshly
# scaffolded reference EA. Numbers reported here are honest, reproducible measurements
# from this kit's own gates — not claims about live-trading performance.
#
# Run:  bash scripts/tools/build_reference_report.sh
# Output: runtime/reference-ea/SampleEA/  (gitignored build artefact)
#         docs/reference-ea/REPORT.md     (committed honest snapshot)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

REF_DIR="runtime/reference-ea"
REF_EA="$REF_DIR/SampleEA/SampleEA.mq5"
REPORT="docs/reference-ea/REPORT.md"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# 1. Scaffold reference EA fresh
rm -rf "$REF_DIR"
mkdir -p "$REF_DIR"
mql5-build --preset stdlib --stack netting --name SampleEA --output "$REF_DIR/" >/dev/null

# 2. Run gates and capture raw output
mql5-lint "$REF_EA" >"$TMP/lint.txt" 2>&1 || true
LINT_EXIT=${PIPESTATUS:-0}
mql5-trader-check --ea "$REF_EA" >"$TMP/trader17.txt" 2>&1 || true
mql5-permission --ea "$REF_EA" --mode PERSONAL   --json >"$TMP/perm-personal.json"   2>&1 || true
mql5-permission --ea "$REF_EA" --mode TEAM       --json >"$TMP/perm-team.json"       2>&1 || true
mql5-permission --ea "$REF_EA" --mode ENTERPRISE --json >"$TMP/perm-enterprise.json" 2>&1 || true
mql5-matrix --mode ENTERPRISE --html "$TMP/matrix.html" 2>&1 \
    | sed "s|$TMP|<tmp>|g" >"$TMP/matrix.txt" || true
mql5-rri-bt --mode TEAM --personas all --json >"$TMP/rri-bt.json" 2>&1 || true

# 3. Extract structured numbers (python for stable parsing)
python3 - "$TMP" >"$TMP/numbers.json" <<'PY'
import json, re, sys
from pathlib import Path
tmp = Path(sys.argv[1])

def read(name):
    return (tmp / name).read_text(encoding="utf-8", errors="replace")

def num(pattern, text, default="?"):
    m = re.search(pattern, text)
    return m.group(1) if m else default

lint = read("lint.txt")
trader = read("trader17.txt")
matrix_txt = read("matrix.txt")

def load(name):
    try:
        return json.loads(read(name))
    except Exception:
        return {}

perm_personal = load("perm-personal.json")
perm_team     = load("perm-team.json")
perm_ent      = load("perm-enterprise.json")
rri_bt        = load("rri-bt.json")

out = {
    "lint": {
        "critical":  num(r"(\d+)\s+critical", lint, "0"),
        "warnings":  num(r"(\d+)\s+warnings", lint, "0"),
        "raw":       lint.strip(),
    },
    "trader17": {
        "passed": num(r"(\d+)\s+PASS,\s*\d+\s+WARN,\s*\d+\s+N-A", trader, "0"),
        "warns":  num(r"PASS,\s*(\d+)\s+WARN", trader, "0"),
        "na":     num(r"WARN,\s*(\d+)\s+N-A", trader, "0"),
        "gate":   "PASS" if int(num(r"(\d+)\s+PASS,\s*\d+\s+WARN,\s*\d+\s+N-A", trader, "0")) >= 15 else "FAIL",
        "raw":    trader.strip(),
    },
    "permission": {
        "PERSONAL":   perm_personal,
        "TEAM":       perm_team,
        "ENTERPRISE": perm_ent,
    },
    "matrix_cli": {
        "raw":  matrix_txt.strip(),
        "note": "mql5-matrix CLI has no EA input; reports defaults only.",
    },
    "rri_bt_matrix": rri_bt.get("matrix", {}),
}
print(json.dumps(out, indent=2))
PY

NUMBERS_FILE="$TMP/numbers.json"

# 4. Render Markdown report
python3 - "$NUMBERS_FILE" "$REPORT" <<'PY'
import json, sys
from pathlib import Path

data = json.loads(Path(sys.argv[1]).read_text())
out_path = Path(sys.argv[2])

lint = data["lint"]
t17 = data["trader17"]
perm = data["permission"]
matrix_cli = data["matrix_cli"]
rri_bt = data["rri_bt_matrix"]

def perm_summary(p):
    if not p:
        return "(no output)"
    mode = p.get("mode", "?")
    all_pass = p.get("all_pass", False)
    layers = p.get("results", {})
    bullets = []
    for k, v in layers.items():
        status = "PASS" if v.get("pass") else "FAIL"
        details = v.get("details", "")
        bullets.append(f"  - {k} ({v.get('name', '')}): **{status}** — {details}")
    return f"**Gate: {'PASS' if all_pass else 'FAIL'}** ({len(layers)} layer(s) executed before fail-fast)\n" + "\n".join(bullets)

md = f"""<!-- Generated by scripts/tools/build_reference_report.sh — do not hand-edit. -->
# Reference EA gate report — honest empirical numbers

> **What this is.** A reproducible snapshot of what this kit's own gates report when
> run against a freshly scaffolded EA (`mql5-build --preset stdlib --stack netting`).
> Numbers below are real outputs from the CLI tools shipped in this repo. They
> describe **how the gates score this kit's own scaffold output**, not whether the
> resulting EA is profitable in live trading — those are different questions.
>
> **Heuristic disclosure.** `Trader-17`, the `8×8 quality matrix`, the `AP-XX`
> anti-pattern IDs, and the `RRI` personas are project-defined heuristics designed
> by this kit. They are opinionated guardrails, **not industry standards or
> certifications**. Treat them accordingly.
>
> **Regenerate with:**
> ```bash
> bash scripts/tools/build_reference_report.sh
> ```

## Reference EA under test

- Preset: `stdlib`
- Stack:  `netting`
- Source: `runtime/reference-ea/SampleEA/SampleEA.mq5` (build artefact, gitignored)
- The scaffold ships with placeholder signal flags (`buySignal = false`,
  `sellSignal = false`), so the EA does not actually trade. The numbers below are
  what the gates report on that out-of-the-box state.

## Lint (`mql5-lint`)

- Critical: **{lint['critical']}**
- Warnings: **{lint['warnings']}**

```
{lint['raw']}
```

Warnings reflect placeholder template state (no trailing stop, no retry, no
trade comment) — not bugs the user introduced.

## Trader-17 checklist (`mql5-trader-check`)

- Result: **{t17['passed']}/17 PASS**, {t17['warns']} WARN, {t17['na']} N-A
- Gate (requires ≥ 15 PASS): **{t17['gate']}**

```
{t17['raw']}
```

`N-A` items require external evidence the kit cannot infer from source alone
(walk-forward, Monte Carlo, multi-broker, overfit, news filter). They are not
silently passed.

## Permission pipeline (`mql5-permission`)

### PERSONAL mode

{perm_summary(perm['PERSONAL'])}

### TEAM mode

{perm_summary(perm['TEAM'])}

### ENTERPRISE mode

{perm_summary(perm['ENTERPRISE'])}

The pipeline is **fail-fast**: once a layer fails, subsequent layers do not run.
That is why Layer 5/6/7 do not appear above — Layer 4 (Trader-17) blocks them
on a bare scaffold.

## 8×8 quality matrix (`mql5-matrix`, standalone)

```
{matrix_cli['raw']}
```

> **Honest note.** `mql5-matrix` standalone does not load EA evidence and defaults
> every cell to N-A. The `0/64 PASS` above is therefore the floor of the CLI, not
> a measured score of `SampleEA.mq5`. To get a meaningful matrix readout you must
> supply RRI evidence (see below) or wire layer 6 of the permission pipeline.

## RRI backtest matrix (`mql5-rri-bt`)

- Cells: {rri_bt.get('total_cells', '?')}
- PASS: {rri_bt.get('passed', '?')}
- WARN: {rri_bt.get('warned', '?')}
- FAIL: {rri_bt.get('failed', '?')}
- Gate (PASS ≥ 56): **{'PASS' if rri_bt.get('gate_pass') else 'FAIL'}**

> **Honest note.** When `--report` is not supplied, `mql5-rri-bt` marks every
> non-`live-canary` cell as PASS by default and every `live-canary` cell as WARN.
> The `56/64` number is therefore a **structural maximum**, not an independent
> verification of `SampleEA`. To exercise the FAIL path, pass `--report` pointing
> at a backtest text containing the word `fail`.

## Reproducibility

| Tool | Version source |
|---|---|
| `vibecodekit-mql5-ea` | `VERSION` file at repo root |
| Python | `requires-python = ">=3.10"` in `pyproject.toml` |
| MetaEditor compile | Optional; layer 2 reports `MetaEditor not found — skipped (non-blocking)` when absent |

_Numbers above are regenerated by `bash scripts/tools/build_reference_report.sh`._
"""

out_path.write_text(md, encoding="utf-8")
print(f"wrote {out_path}")
PY

echo "Done. Report at: $REPORT"
