//+------------------------------------------------------------------+
//| EAName.mq5 — ML/ONNX EA with Python bridge                      |
//| Generated by vibecodekit-mql5-ea scaffold                        |
//| Phase D full: uses COnnxLoader.mqh for native inference           |
//| This scaffold uses Python bridge for training + signal            |
//+------------------------------------------------------------------+
#property copyright "EAName"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include "CPipNormalizer.mqh"
#include "CRiskGuard.mqh"

input int    InpMagic        = 99999;
input double InpRiskPercent  = 1.0;
input int    InpSLPips       = 50;
input int    InpTPPips       = 100;
input double InpDailyLoss    = 5.0;
input int    InpMaxPos       = 3;
input string InpModelURL     = "http://127.0.0.1:8000/predict";
input int    InpTimeout      = 5000;

CTrade         trade;
CPipNormalizer pipNorm;
CRiskGuard     riskGuard;

int OnInit()
{
    if(!pipNorm.Init(_Symbol)) return INIT_FAILED;
    if(!riskGuard.Init(InpDailyLoss, InpMaxPos, InpMagic, "EAName"))
        return INIT_FAILED;
    trade.SetExpertMagicNumber(InpMagic);
    EventSetTimer(60);
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) { EventKillTimer(); }

void OnTimer()
{
    if(!riskGuard.CanOpenTrade()) return;

    // Prepare feature data
    double close[];
    ArraySetAsSeries(close, true);
    if(CopyClose(_Symbol, _Period, 0, 60, close) < 60) return;

    string features = "[";
    for(int i = 0; i < 60; i++)
    {
        if(i > 0) features += ",";
        features += DoubleToString(close[i], (int)pipNorm.Digits());
    }
    features += "]";

    string body = "{\"symbol\":\"" + _Symbol + "\",\"features\":" + features + "}";
    string headers = "Content-Type: application/json\r\n";
    char data[], result[];
    string result_headers;
    StringToCharArray(body, data);

    int res = WebRequest("POST", InpModelURL, headers, InpTimeout, data,
                         result, result_headers);
    if(res != 200) return;

    string response = CharArrayToString(result);

    if(StringFind(response, "\"buy\"") >= 0)
    {
        double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double sl  = ask - pipNorm.Pips(InpSLPips);
        double tp  = ask + pipNorm.Pips(InpTPPips);
        double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk_money, InpSLPips);
        trade.Buy(lots, _Symbol, ask, sl, tp, "EAName ml-buy");
    }
    else if(StringFind(response, "\"sell\"") >= 0)
    {
        double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double sl  = bid + pipNorm.Pips(InpSLPips);
        double tp  = bid - pipNorm.Pips(InpTPPips);
        double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk_money, InpSLPips);
        trade.Sell(lots, _Symbol, bid, sl, tp, "EAName ml-sell");
    }
}

void OnTick() { /* signals via OnTimer, not OnTick (AP-17 compliant) */ }
//+------------------------------------------------------------------+
