//+------------------------------------------------------------------+
//| EAName.mq5 — Standard Library EA (hedging account)               |
//| Generated by vibecodekit-mql5-ea scaffold                        |
//+------------------------------------------------------------------+
#property copyright "EAName"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\AccountInfo.mqh>
#include "CPipNormalizer.mqh"
#include "CRiskGuard.mqh"
#include "CMagicRegistry.mqh"

input int    InpMagic       = 12345;
input double InpRiskPercent = 1.0;
input int    InpSLPips      = 50;
input int    InpTPPips      = 100;
input double InpDailyLoss   = 5.0;
input int    InpMaxPos      = 5;

CTrade         trade;
CPipNormalizer pipNorm;
CRiskGuard     riskGuard;
CMagicRegistry magicReg;

int OnInit()
{
    if(!pipNorm.Init(_Symbol))   return INIT_FAILED;
    if(!riskGuard.Init(InpDailyLoss, InpMaxPos, InpMagic, "EAName"))
        return INIT_FAILED;
    if(!magicReg.Reserve("EAName", _Symbol, InpMagic))
        return INIT_FAILED;

    trade.SetExpertMagicNumber(InpMagic);
    trade.SetDeviationInPoints(10);

    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
    magicReg.Release();
}

void OnTick()
{
    if(!riskGuard.CanOpenTrade()) return;

    // --- HEDGING: multiple positions allowed per symbol ---
    bool buySignal  = false;
    bool sellSignal = false;

    if(buySignal)
    {
        double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double sl  = ask - pipNorm.Pips(InpSLPips);
        double tp  = ask + pipNorm.Pips(InpTPPips);
        double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk_money, InpSLPips);
        trade.Buy(lots, _Symbol, ask, sl, tp, "EAName hedge-buy");
    }

    if(sellSignal)
    {
        double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double sl  = bid + pipNorm.Pips(InpSLPips);
        double tp  = bid - pipNorm.Pips(InpTPPips);
        double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk_money, InpSLPips);
        trade.Sell(lots, _Symbol, bid, sl, tp, "EAName hedge-sell");
    }
}
//+------------------------------------------------------------------+
