//+------------------------------------------------------------------+
//| EAName.mq5 — Portfolio basket EA (hedging, multi-symbol)         |
//| Generated by vibecodekit-mql5-ea scaffold                        |
//+------------------------------------------------------------------+
#property copyright "EAName"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include "CPipNormalizer.mqh"
#include "CRiskGuard.mqh"
#include "CMagicRegistry.mqh"

input int    InpMagicBase    = 20000;
input double InpRiskPercent  = 0.5;
input int    InpSLPips       = 50;
input int    InpTPPips       = 100;
input double InpDailyLoss    = 5.0;
input int    InpMaxPos       = 10;
input string InpSymbols      = "EURUSD,GBPUSD,USDJPY";

#define MAX_SYMBOLS 10

CTrade         trade;
CPipNormalizer pipNorms[MAX_SYMBOLS];
CRiskGuard     riskGuard;
CMagicRegistry magicRegs[MAX_SYMBOLS];
string         symbols[MAX_SYMBOLS];
int            symbolCount;

int OnInit()
{
    if(!riskGuard.Init(InpDailyLoss, InpMaxPos, InpMagicBase, "EAName"))
        return INIT_FAILED;

    symbolCount = 0;
    string parts[];
    int n = StringSplit(InpSymbols, ',', parts);
    for(int i = 0; i < n && i < MAX_SYMBOLS; i++)
    {
        StringTrimLeft(parts[i]);
        StringTrimRight(parts[i]);
        symbols[i] = parts[i];
        if(!pipNorms[i].Init(symbols[i])) return INIT_FAILED;
        if(!magicRegs[i].Reserve("EAName", symbols[i], InpMagicBase + i))
            return INIT_FAILED;
        symbolCount++;
    }
    trade.SetDeviationInPoints(10);
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
    for(int i = 0; i < symbolCount; i++)
        magicRegs[i].Release();
}

void OnTick()
{
    if(!riskGuard.CanOpenTrade()) return;

    for(int i = 0; i < symbolCount; i++)
    {
        trade.SetExpertMagicNumber(InpMagicBase + i);
        // --- HEDGING: multiple positions per symbol allowed ---
        bool buySignal  = false;
        bool sellSignal = false;

        if(buySignal)
        {
            double ask = SymbolInfoDouble(symbols[i], SYMBOL_ASK);
            double sl  = ask - pipNorms[i].Pips(InpSLPips);
            double tp  = ask + pipNorms[i].Pips(InpTPPips);
            double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
            double lots = pipNorms[i].LotForRisk(risk_money, InpSLPips);
            trade.Buy(lots, symbols[i], ask, sl, tp, "EAName hedge-basket");
        }
        if(sellSignal)
        {
            double bid = SymbolInfoDouble(symbols[i], SYMBOL_BID);
            double sl  = bid + pipNorms[i].Pips(InpSLPips);
            double tp  = bid - pipNorms[i].Pips(InpTPPips);
            double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
            double lots = pipNorms[i].LotForRisk(risk_money, InpSLPips);
            trade.Sell(lots, symbols[i], bid, sl, tp, "EAName hedge-basket");
        }
    }
}
//+------------------------------------------------------------------+
