//+------------------------------------------------------------------+
//| EAName.mq5 — Wizard-composable EA (CExpert-based, netting)       |
//| Generated by vibecodekit-mql5-ea scaffold                        |
//| Based on Mashnin's Advanced MQL5 approach                        |
//+------------------------------------------------------------------+
#property copyright "EAName"
#property version   "1.00"
#property strict

#include <Expert\Expert.mqh>
#include <Expert\Signal\SignalMACD.mqh>
#include <Expert\Signal\SignalSAR.mqh>
#include <Expert\Trailing\TrailingParabolicSAR.mqh>
#include <Expert\Money\MoneyFixedRisk.mqh>
#include "CPipNormalizer.mqh"

input string InpExpertName  = "EAName";
input int    InpMagic       = 54321;
input double InpRiskPercent = 1.0;
input int    InpSLPips      = 50;

// MACD signal params
input int    InpMACDFast    = 12;
input int    InpMACDSlow    = 26;
input int    InpMACDSignal  = 9;

// SAR signal params
input double InpSARStep     = 0.02;
input double InpSARMax      = 0.2;

CExpert        expert;
CPipNormalizer pipNorm;

int OnInit()
{
    if(!pipNorm.Init(_Symbol)) return INIT_FAILED;

    if(!expert.Init(_Symbol, _Period, true, InpMagic))
        return INIT_FAILED;

    // Signal: MACD + SAR composite
    CExpertSignal *signal = new CExpertSignal();
    if(!expert.InitSignal(signal)) return INIT_FAILED;

    CSignalMACD *macd = new CSignalMACD();
    macd.PeriodFast(InpMACDFast);
    macd.PeriodSlow(InpMACDSlow);
    macd.PeriodSignal(InpMACDSignal);
    signal.AddFilter(macd);

    CSignalSAR *sar = new CSignalSAR();
    sar.Step(InpSARStep);
    sar.Maximum(InpSARMax);
    signal.AddFilter(sar);

    // Trailing: Parabolic SAR
    CTrailingPSAR *trail = new CTrailingPSAR();
    trail.Step(InpSARStep);
    trail.Maximum(InpSARMax);
    if(!expert.InitTrailing(trail)) return INIT_FAILED;

    // Money: Fixed risk %
    CMoneyFixedRisk *money = new CMoneyFixedRisk();
    money.Percent(InpRiskPercent);
    if(!expert.InitMoney(money)) return INIT_FAILED;

    if(!expert.InitTrade(InpMagic)) return INIT_FAILED;
    expert.OnInit();
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) { expert.OnDeinit(); }
void OnTick()                   { expert.OnTick(); }
void OnTrade()                  { expert.OnTrade(); }
//+------------------------------------------------------------------+
