//+------------------------------------------------------------------+
//| EAName.mq5 — trend EA (netting)                               |
//| Generated by vibecodekit-mql5-ea scaffold · Phase D              |
//+------------------------------------------------------------------+
#property copyright "EAName"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include "CPipNormalizer.mqh"
#include "CRiskGuard.mqh"

input int    InpMagic       = 12345;
input double InpRiskPercent = 1.0;
input int    InpSLPips      = 50;
input int    InpTPPips      = 100;

CTrade         trade;
CPipNormalizer pipNorm;
CRiskGuard     riskGuard;

int OnInit()
{
    if(!pipNorm.Init(_Symbol)) return INIT_FAILED;
    if(!riskGuard.Init(5.0, 3, InpMagic, "EAName")) return INIT_FAILED;
    trade.SetExpertMagicNumber(InpMagic);
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) {}

void OnTick()
{
    if(!riskGuard.CanOpenTrade()) return;
    // --- trend strategy logic here ---
}
//+------------------------------------------------------------------+
