//+------------------------------------------------------------------+
//| EAName.mq5 — Standard Library EA (netting account)               |
//| Generated by vibecodekit-mql5-ea scaffold                        |
//+------------------------------------------------------------------+
#property copyright "EAName"
#property version   "1.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\AccountInfo.mqh>
#include "CPipNormalizer.mqh"
#include "CRiskGuard.mqh"
#include "CMagicRegistry.mqh"

input int    InpMagic       = 12345;   // Magic number
input double InpRiskPercent = 1.0;     // Risk per trade (%)
input int    InpSLPips      = 50;      // Stop-loss (pips)
input int    InpTPPips      = 100;     // Take-profit (pips)
input double InpDailyLoss   = 5.0;    // Max daily loss (%)
input int    InpMaxPos      = 3;       // Max open positions

CTrade         trade;
CPipNormalizer pipNorm;
CRiskGuard     riskGuard;
CMagicRegistry magicReg;

int OnInit()
{
    if(!pipNorm.Init(_Symbol))
    {
        Print("[EAName] CPipNormalizer init failed");
        return INIT_FAILED;
    }
    if(!riskGuard.Init(InpDailyLoss, InpMaxPos, InpMagic, "EAName"))
    {
        Print("[EAName] CRiskGuard init failed");
        return INIT_FAILED;
    }
    if(!magicReg.Reserve("EAName", _Symbol, InpMagic))
    {
        Print("[EAName] Magic number collision");
        return INIT_FAILED;
    }

    trade.SetExpertMagicNumber(InpMagic);
    trade.SetDeviationInPoints(10);
    trade.SetTypeFilling(ORDER_FILLING_FOK);

    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
    magicReg.Release();
}

void OnTick()
{
    if(!riskGuard.CanOpenTrade()) return;

    // --- YOUR STRATEGY LOGIC HERE ---
    // Example: simple signal placeholder
    bool buySignal  = false;  // Replace with your buy condition
    bool sellSignal = false;  // Replace with your sell condition

    if(buySignal)
    {
        double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double sl  = ask - pipNorm.Pips(InpSLPips);
        double tp  = ask + pipNorm.Pips(InpTPPips);
        double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk_money, InpSLPips);

        trade.Buy(lots, _Symbol, ask, sl, tp, "EAName buy");
    }

    if(sellSignal)
    {
        double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double sl  = bid + pipNorm.Pips(InpSLPips);
        double tp  = bid - pipNorm.Pips(InpTPPips);
        double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPercent / 100.0;
        double lots = pipNorm.LotForRisk(risk_money, InpSLPips);

        trade.Sell(lots, _Symbol, bid, sl, tp, "EAName sell");
    }
}
//+------------------------------------------------------------------+
